version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=home.settings
    command: >
      sh -c "python manage.py migrate &&
             python manage.py create_timeslots &&
             python manage.py create_rooms &&
             python manage.py runserver 0.0.0.0:8000"
